# Check sid duplicates

In [1]:
import pandas as pd
import config
from utils import bagz_utils

BASE_DIR: /usr/local/google/home/stellasyan/Documents/llm_internalization

In [2]:
df = bagz_utils.read_parquet(config.META_W_ALL_SID) 
df.head(3)

,asin,description,title,imUrl,salesRank,categories,price,related,brand,fine_category,formatted_text,embedding,llama_embedding,sid,formatted_sid
0,0205616461,"As we age, our once youthful, healthy skin suc...",Bio-Active Anti-Aging Serum (Firming Ultra-Hyd...,http://ecx.images-amazon.com/images/I/41DecrGO...,"{'Arts, Crafts & Sewing': None, 'Automotive': ...","[[Beauty, Skin Care, Face, Creams & Moisturize...",NaN,None,None,Creams & Moisturizers,\nCreams & Moisturizers\n \nBio-Active Anti-A...,"[0.05493081733584404, 0.010757452808320522, 0....","[-0.0031871795654296875, 0.0275421142578125, -...","[30, 233, 69, 0]",A30 B233 C69 D0
1,0558925278,Mineral Powder Brush--Apply powder or mineral ...,Eco Friendly Ecotools Quality Natural Bamboo C...,http://ecx.images-amazon.com/images/I/51L%2BzY...,"{'Arts, Crafts & Sewing': None, 'Automotive': ...","[[Beauty, Tools & Accessories, Makeup Brushes ...",NaN,None,None,Brushes & Applicators,\nBrushes & Applicators\n \nEco Friendly Ecot...,"[0.060298189520835876, -0.04054930433630943, -...","[0.004978179931640625, 0.0394287109375, 0.0340...","[186, 20, 60, 0]",A186 B20 C60 D0
2,0733001998,"From the Greek island of Chios, this Mastiha b...",Mastiha Body Lotion,http://ecx.images-amazon.com/images/I/311WK5y1...,"{'Arts, Crafts & Sewing': None, 'Automotive': ...","[[Beauty, Skin Care, Body, Moisturizers, Lotio...",NaN,None,None,Lotions,\nLotions\n \nMastiha Body Lotion\nFrom the G...,"[0.047420427203178406, 0.009653563611209393, -...","[-0.01096343994140625, 0.002483367919921875, 0...","[78, 117, 139, 0]",A78 B117 C139 D0

In [5]:
# Step 1: Extract the first three tokens
df['prefix_3'] = df['formatted_sid'].apply(lambda x: ' '.join(x.split()[:3]))

# Step 2: Count duplicates per prefix
group_counts = df.groupby('prefix_3').size().reset_index(name='count')

# Step 3: Sort groups by the number of duplicates (descending)
group_counts_sorted = group_counts.sort_values(by='count', ascending=False)

print(group_counts_sorted)

              prefix_3  count
167000     A35 B55 C50     70
132391   A231 B94 C237     64
76961    A178 B82 C195     60
59411   A159 B210 C150     48
75321   A178 B137 C179     42
...                ...    ...
78584     A18 B19 C244      1
78586      A18 B19 C67      1
78587      A18 B19 C87      1
78588    A18 B190 C102      1
78574    A18 B185 C255      1

[224483 rows x 2 columns]

In [7]:
# Suppose you want the group with prefix "A30 B233 C69"
prefix = "A35 B55 C50"

group_rows = df[df['prefix_3'] == prefix]

print(group_rows[['brand', 'title']])

       brand                                              title
232689  None  MoYou-London Nail Art Image Plate Rebel Collec...
234192  None  MoYou-London Nail Art Image Plate Princess Col...
234196  None  MoYou-London Nail Art Image Plate Frenchy Coll...
234197  None  MoYou-London Nail Art Image Plate Frenchy Coll...
234198  None  MoYou-London Nail Art Image Plate Frenchy Coll...
...      ...                                                ...
241490  None  MoYou-London Nail Art Image Plate Artist Colle...
241491  None  MoYou-London Nail Art Image Plate Artist Colle...
241492  None  MoYou-London Nail Art Image Plate Artist Colle...
241493  None  MoYou-London Nail Art Image Plate Rockstar Col...
241494  None  MoYou-London Nail Art Image Plate Artist Colle...

[70 rows x 2 columns]

# Check review dataframe

In [17]:
import pandas as pd
import config
from utils import bagz_utils

In [19]:
meta_df = bagz_utils.read_parquet(config.META_W_ALL_SID) 
meta_df.head(3)

,asin,description,title,imUrl,salesRank,categories,price,related,brand,fine_category,formatted_text,embedding,llama_embedding,sid,formatted_sid
0,0205616461,"As we age, our once youthful, healthy skin suc...",Bio-Active Anti-Aging Serum (Firming Ultra-Hyd...,http://ecx.images-amazon.com/images/I/41DecrGO...,"{'Arts, Crafts & Sewing': None, 'Automotive': ...","[[Beauty, Skin Care, Face, Creams & Moisturize...",NaN,None,None,Creams & Moisturizers,\nCreams & Moisturizers\n \nBio-Active Anti-A...,"[0.05493081733584404, 0.010757452808320522, 0....","[-0.0031871795654296875, 0.0275421142578125, -...","[30, 233, 69, 0]",A30 B233 C69 D0
1,0558925278,Mineral Powder Brush--Apply powder or mineral ...,Eco Friendly Ecotools Quality Natural Bamboo C...,http://ecx.images-amazon.com/images/I/51L%2BzY...,"{'Arts, Crafts & Sewing': None, 'Automotive': ...","[[Beauty, Tools & Accessories, Makeup Brushes ...",NaN,None,None,Brushes & Applicators,\nBrushes & Applicators\n \nEco Friendly Ecot...,"[0.060298189520835876, -0.04054930433630943, -...","[0.004978179931640625, 0.0394287109375, 0.0340...","[186, 20, 60, 0]",A186 B20 C60 D0
2,0733001998,"From the Greek island of Chios, this Mastiha b...",Mastiha Body Lotion,http://ecx.images-amazon.com/images/I/311WK5y1...,"{'Arts, Crafts & Sewing': None, 'Automotive': ...","[[Beauty, Skin Care, Body, Moisturizers, Lotio...",NaN,None,None,Lotions,\nLotions\n \nMastiha Body Lotion\nFrom the G...,"[0.047420427203178406, 0.009653563611209393, -...","[-0.01096343994140625, 0.002483367919921875, 0...","[78, 117, 139, 0]",A78 B117 C139 D0

In [4]:
review_df = pd.read_json(config.AMAZON_REVIEW_DATASET, lines=True)
display(review_df.head(3))
print(review_df.shape)

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A1YJEY40YUW4SE,7806397051,Andrea,"[3, 4]",Very oily and creamy. Not at all what I expect...,1,Don't waste your money,1391040000,"01 30, 2014"
1,A60XNB876KYML,7806397051,Jessica H.,"[1, 1]",This palette was a decent price and I was look...,3,OK Palette!,1397779200,"04 18, 2014"
2,A3G6XNM240RMWA,7806397051,Karen,"[0, 1]",The texture of this concealer pallet is fantas...,4,great quality,1378425600,"09 6, 2013"

(198502, 9)

In [5]:
review_df["reviewerID"].nunique()

22363

In [13]:
sorted_df = review_df.sort_values(by=['reviewerID', 'unixReviewTime'])
user_sequences = sorted_df.groupby('reviewerID')['asin'].agg(list).reset_index()

In [21]:
# Step 1: Merge review_df with meta_df to get formatted_sid
merged_df = review_df.merge(meta_df[['asin', 'formatted_sid']], on='asin', how='left')
merged_df.head(3)

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,formatted_sid
0,A1YJEY40YUW4SE,7806397051,Andrea,"[3, 4]",Very oily and creamy. Not at all what I expect...,1,Don't waste your money,1391040000,"01 30, 2014",A207 B248 C148 D0
1,A60XNB876KYML,7806397051,Jessica H.,"[1, 1]",This palette was a decent price and I was look...,3,OK Palette!,1397779200,"04 18, 2014",A207 B248 C148 D0
2,A3G6XNM240RMWA,7806397051,Karen,"[0, 1]",The texture of this concealer pallet is fantas...,4,great quality,1378425600,"09 6, 2013",A207 B248 C148 D0

In [22]:
# Step 2: Sort by reviewerID and unixReviewTime
sorted_df = merged_df.sort_values(by=['reviewerID', 'unixReviewTime'])
sorted_df.head(3)

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,formatted_sid
145572,A00414041RD0BXM6WK0GX,B007IY97U0,Sarah Hale,"[0, 0]","Good quality wig, but the blonde is much more ...",3,Three Stars,1405296000,"07 14, 2014",A63 B51 C159 D0
152551,A00414041RD0BXM6WK0GX,B00870XLDS,Sarah Hale,"[0, 0]",Very thin and not as long as the photos :( Aft...,2,( After waiting over a month to receive this w...,1405296000,"07 14, 2014",A63 B88 C66 D0
155883,A00414041RD0BXM6WK0GX,B008MIRO88,Sarah Hale,"[0, 0]",Very thin and not as long as the photos :( Aft...,1,( After waiting over a month to receive this w...,1405296000,"07 14, 2014",A63 B140 C62 D0

In [25]:
# Step 3: Generate sequences of formatted_sid for each user
user_sequences = sorted_df.groupby('reviewerID')['formatted_sid'].agg(list).reset_index()
user_sequences.rename(columns={'formatted_sid': 'sequence'}, inplace=True)
user_sequences.head(10)

              reviewerID                                           sequence
0  A00414041RD0BXM6WK0GX  [A63 B51 C159 D0, A63 B88 C66 D0, A63 B140 C62...
1  A00473363TJ8YSZ3YAGG9  [A36 B171 C196 D2, A33 B24 C20 D0, A139 B114 C...
2  A00700212KB3K0MVESPIY  [A88 B125 C235 D0, A77 B123 C253 D0, A55 B70 C...
3   A0078719IR14X3NNUG0F  [A229 B238 C141 D0, A88 B195 C142 D0, A35 B187...
4  A01198201H0E3GHV2Z17I  [A77 B96 C200 D0, A229 B56 C251 D0, A219 B73 C...
5  A02155413BVL8D0G7X6DN  [A247 B21 C61 D0, A118 B17 C125 D0, A192 B97 C...
6  A02849582PREZYNEI31CV  [A229 B145 C65 D0, A229 B242 C56 D0, A229 B191...
7  A029527620Q3SK5XW16RR  [A73 B84 C137 D0, A200 B136 C210 D0, A30 B119 ...
8  A03236882LUP4ARMDDMXU  [A212 B47 C6 D0, A73 B145 C10 D0, A199 B4 C201...
9  A03364251DGXSGA9PSR99  [A155 B0 C69 D0, A211 B18 C179 D0, A211 B18 C2...

In [19]:
records = bagz_utils.read_record(config.USER_SEQUENCE)
records[0]

{'id': 1,
 'reviewerID': 'A00414041RD0BXM6WK0GX',
 'sequence': ['A63 B51 C159 D0',
  'A63 B88 C66 D0',
  'A63 B140 C62 D0',
  'A159 B162 C72 D0',
  'A159 B230 C177 D1',
  'A159 B177 C121 D4'],
 'asin_sequence': ['B007IY97U0',
  'B00870XLDS',
  'B008MIRO88',
  'B00BQYYMN0',
  'B00GRTQBTM',
  'B00HFP4JZU']}

In [23]:
from collections import Counter

# Step 1: Extract the last element of asin_sequence for each user
last_asins = [record['asin_sequence'][-1] for record in records]

# Step 2: Count frequency of each last ASIN
last_asin_counter = Counter(last_asins)

# Step 3: Get top-k most popular last ASINs
k = 10
top_k_last_asins = [asin for asin, _ in last_asin_counter.most_common(k)]
print("Top-k most popular last ASINs:", top_k_last_asins)

# Step 4: Compute recall@k
# Percentage of users whose last ASIN is in the top-k
hits = sum(1 for asin in last_asins if asin in top_k_last_asins)
recall_at_k = hits / len(last_asins)

print(f"Recall@{k}: {recall_at_k:.4f}")

Top-k most popular last ASINs: ['B00I6CRX04', 'B00A51LI1O', 'B00A76CPUA', 'B008U1Q4DI', 'B0069FDR96', 'B00KQBR9FM', 'B007BLN17K', 'B00JF3RYPM', 'B0043OYFKU', 'B007O7AZBG']
Recall@10: 0.0224

In [ ]:
from collections import Counter

# Step 1: Extract the last element of asin_sequence for each user
last_sids = [record['sequence'][-1] for record in records]

# Step 2: Count frequency of each last ASIN
last_sid_counter = Counter(last_sids)

# Step 3: Get top-k most popular last ASINs
k = 10
top_k_last_sids = [sid for sid, _ in last_sid_counter.most_common(k)]
print("Top-k most popular last ASINs:", top_k_last_asins)

# Step 4: Compute recall@k
# Percentage of users whose last ASIN is in the top-k
hits = sum(1 for asin in last_sids if asin in top_k_last_sids)
recall_at_k = hits / len(last_sids)

print(f"Recall@{k}: {recall_at_k:.4f}")

# Load Checkpoint

In [30]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import config

/usr/local/google/home/stellasyan/miniconda3/envs/torch_rl/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [31]:
MODEL_SAVE_DIR = config.MODEL_DIR / "all_sid_aligned_model"

def load_model_tokenizer():
    model = AutoModelForCausalLM.from_pretrained(MODEL_SAVE_DIR)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_SAVE_DIR)

    return model, tokenizer

# Check training data

In [47]:
import pandas as pd
import config
from utils import bagz_utils
import bagz

In [48]:
data_reader = bagz.Reader(config.EVAL_DATA)
data_reader[3250]

b'{"uid": 3251, "input": "A29 B145 C84 D0; A218 B229 C83 D0; A14 B191 C102 D0; A162 B54 C67 D0; A232 B204 C4 D0; A232 B16 C108 D1; A218 B36 C153 D0; A108 B203 C121 D0; A162 B136 C155 D1; A239 B144 C137 D0; A109 B144 C125 D0; A14 B198 C122 D1; A103 B95 C80 D1; A211 B132 C147 D0; A186 B122 C240 D0", "target": "A139 B2 C231 D0"}'

In [49]:
import json

json.loads(data_reader[10].decode())

{'uid': 11,
 'input': 'A16 B119 C182 D0; A133 B231 C2 D2; A22 B43 C180 D0; A196 B228 C196 D0; A69 B182 C64 D0',
 'target': 'A7 B43 C240 D0'}

# Upper bound

In [7]:
import config
import bagz
import json
from collections import Counter

In [6]:
data_reader = bagz.Reader(config.EVAL_DATA)
data = [json.loads(record.decode()) for record in data_reader]
print(len(data))

data[0]

22363

{'uid': 1,
 'input': 'A63 B51 C159 D0; A63 B88 C66 D0; A63 B140 C62 D0; A159 B162 C72 D0',
 'target': 'A159 B230 C177 D1'}

In [15]:
# Count how many times each target appears
target_counts = Counter(d['target'] for d in data)

# Get top-k most common targets
k = 5
# top_k_targets = target_counts.most_common(k)      # get item and count
top_k_targets = [t for t, _ in target_counts.most_common(k)]    # only get items


print(top_k_targets)

['A35 B67 C229 D0', 'A229 B0 C84 D0', 'A229 B238 C141 D0', 'A154 B42 C227 D0', 'A229 B93 C183 D0']

In [16]:
# Step 3: Compute recall@k
hits = sum(1 for d in data if d['target'] in top_k_targets)
recall_at_k = hits / len(data)

print(f"Recall@{k}: {recall_at_k:.4f}")

Recall@5: 0.0123